"""create frame and block table

Revision ID: 1fc165a90d68
Revises:
Create Date: 2021-03-12 15:41:50.150507

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1fc165a90d68"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "frames",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "blocks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("frame_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["frame_id"],
            ["frames.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("blocks")
    op.drop_table("frames")
    # ### end Alembic commands ###
